CREATE DATABASE TraLaLa;

GRANT ALTER, SELECT,INSERT,UPDATE,DELETE,CREATE,DROP, INDEX 
           ON TraLaLa.*
           TO sd@'%'
           IDENTIFIED BY 'sd';

GRANT ALTER, SELECT,INSERT,UPDATE,DELETE,CREATE,DROP, INDEX
           ON TraLaLa.*
           TO sd@localhost
           IDENTIFIED BY 'sd';